### ISSUE TITLE
Error: Cannot find module './src/character_count'

### ISSUE THREAD

**Issue by jankeesvw** [eelcoj/stimulus-form-utilities#1]
I just tried installing this module, but unfortunately I can't get it to work. I get this error:

`Error: Cannot find module './src/character_count'`

![image](https://user-images.githubusercontent.com/167882/71414143-da9cb480-2655-11ea-8df4-9326d8964632.png)

**Comment by eelcoj** [comment]
I just updated the packaging script. Should be good now. 

https://github.com/eelcoj/stimulus-form-utilities/releases/tag/v1.0.5
